/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UmlUiModule extends AbstractUmlUiModule {

	public UmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
