/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui.quickfix;

import javax.swing.text.BadLocationException;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.xtext.example.mydsl.validation.UmlValidator;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class UmlQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(UmlValidator.INVALID_NAME)
	public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				String firstLetter;
				try {
					firstLetter = xtextDocument.get(issue.getOffset(), 1);
					xtextDocument.replace(issue.getOffset(), 1, firstLetter.toUpperCase());
				} catch (org.eclipse.jface.text.BadLocationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}
	
	@Fix(UmlValidator.NO_CLASS_CONTENT)
	public void generateClassContent(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Generate class content", "Generate attributes and functions container", "", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument= context.getXtextDocument();
				String toAdd = "parameter {"
						+ "}"
						+ "function {"
						+ "}";
				try {
					xtextDocument.replace(issue.getOffset(), toAdd.length(), toAdd);
				} catch (org.eclipse.jface.text.BadLocationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			
		});
	}
	

}
